swagger: '2.0'
info:
  version: '1.0.0'
  title: My Notes API
  description: API for managing notes
host: localhost:8080
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /notes:
    get:
      summary: Get all notes
      description: Returns a list of all notes.
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'
        '500':
          description: Internal server error
    post:
      summary: Create a new note
      description: Creates a new note.
      parameters:
        - name: note
          in: body
          description: Note object to create
          required: true
          schema:
            $ref: '#/definitions/Note'
      responses:
        '200':
          description: Note created successfully
          schema:
            type: object
            properties:
              message:
                type: string
              note_id:
                type: integer
                format: int64
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /notes/{id}:
    get:
      summary: Get a note by ID
      description: Returns a single note by ID.
      parameters:
        - name: id
          in: path
          description: ID of the note to get
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Note'
        '404':
          description: Note not found
        '500':
          description: Internal server error
    patch:
      summary: Update a note by ID
      description: Updates a note by ID.
      parameters:
        - name: id
          in: path
          description: ID of the note to update
          required: true
          type: integer
          format: int64
        - name: note
          in: body
          description: Updated note object
          required: true
          schema:
            $ref: '#/definitions/Note'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Note not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a note by ID
      description: Deletes a note by ID.
      parameters:
        - name: id
          in: path
          description: ID of the note to delete
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: No content
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

definitions:
  Note:
    type: object
    properties:
      id:
        type: integer
        format: int64
      created_at:
        type: string
        format: date-time
      author_id:
        type: integer
        format: int64
      text:
        type: string
      is_public:
        type: boolean
