version: '3.8'

services:
  go-notes-service:
    build:
      context: .
      dockerfile: Dockerfile.go
    ports:
      - "8080:8080"
    depends_on:
      - db

  python-auth-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "jet-style"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5452:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
